// Copyright (c) Reality Collective. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace RealityCollective.UXManager.Editor
{
    /// <summary>
    /// Editor tool to auto-generate LocalizationKeys.g.cs from the default locale catalog.
    /// Similar to ScreenNamesGenerator, this creates constants for all localization keys.
    /// </summary>
    public static class LocalizationKeysGenerator
    {
        private const string OutputPath = "Assets/ServiceProvidersProfile/LocalizationKeys.g.cs";
        private const string DefaultCatalogPath = "Assets/UX/Localization/Catalogs/en-US.json";
        private const string Namespace = "yperea";

        [MenuItem("Reality Toolkit/UX Manager/Generate Localization Keys")]
        public static void Generate()
        {
            if (!File.Exists(DefaultCatalogPath))
            {
                Debug.LogError($"Default catalog not found at: {DefaultCatalogPath}");
                return;
            }

            var keys = LoadKeysFromDefaultCatalog();
            if (keys == null || keys.Count == 0)
            {
                Debug.LogError("No keys found in default catalog.");
                return;
            }

            GenerateKeysClass(keys);
            AssetDatabase.Refresh();
            Debug.Log($"[LocalizationKeysGenerator] Generated {keys.Count} localization keys in {OutputPath}");
        }

        private static List<string> LoadKeysFromDefaultCatalog()
        {
            try
            {
                string json = File.ReadAllText(DefaultCatalogPath);
                var catalog = JsonUtility.FromJson<LocalizationCatalog>(json);
                return catalog?.keys?.Keys.OrderBy(k => k).ToList();
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"[LocalizationKeysGenerator] Error loading default catalog: {ex.Message}");
                return null;
            }
        }

        private static void GenerateKeysClass(List<string> keys)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated by LocalizationKeysGenerator.");
            sb.AppendLine("// Do not modify this file directly.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated localization key constants from the default (en-US) locale catalog.");
            sb.AppendLine("    /// Use these constants with ILocalizationService.GetString() for type-safe localization lookups.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class LocalizationKeys");
            sb.AppendLine("    {");

            foreach (var key in keys)
            {
                // Convert key to C# constant name (e.g., "mainscreen_time" -> "MainscreenTime")
                string constantName = ToPascalCase(key);
                sb.AppendLine($"        /// <summary>{key}</summary>");
                sb.AppendLine($"        public const string {constantName} = \"{key}\";");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath) ?? "Assets");
            File.WriteAllText(OutputPath, sb.ToString());
        }

        private static string ToPascalCase(string key)
        {
            var parts = key.Split('_');
            var sb = new StringBuilder();
            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    sb.Append(char.ToUpper(part[0]));
                    sb.Append(part.Substring(1));
                }
            }
            return sb.ToString();
        }

        [System.Serializable]
        private class LocalizationCatalog
        {
            public string locale;
            public string version;
            public Dictionary<string, string> keys = new Dictionary<string, string>();
        }
    }
}
